version: 2

models:
  - name: addresses_silver
    description: "bronze 레이어의 주소 데이터를 정제한 모델입니다. 주소를 대문자로 변환하고, 총 지출을 decimal로 캐스팅하며, 도시 정보를 cities_silver 모델에서 매칭합니다."
    columns:
      - name: company_id
        description: "회사 식별자입니다."
        tests:
          - not_null

      - name: address
        description: "대문자로 변환된 주소입니다."
        tests:
          - not_null

      - name: total_spend
        description: "decimal 형식으로 변환된 총 지출 금액입니다."
        tests:
          - not_null

      - name: city
        description: "주소에서 추출된 도시 정보입니다. cities_silver 모델과 매칭되며, 매칭되지 않을 경우 'OTHER'로 처리됩니다."
        tests:
          - not_null

  - name: cities_silver
    description: "bronze 레이어의 도시 데이터를 정제한 모델입니다. 도시 이름에서 특수문자(*)를 제거하고, 대문자로 변환한 후 특정 국가명을 제외합니다."
    columns:
      - name: city
        description: "정제된 도시 이름입니다. 대문자로 변환되고, 특수문자 제거 및 특정 국가명 제외 처리가 적용됩니다."
        tests:
          - not_null
          - unique